/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface CommitmentChainInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_ADMIN_ROLE"
      | "EMERGENCY_ROLE"
      | "LAWYER_ROLE"
      | "POLICE_ROLE"
      | "UPGRADE_INTERFACE_VERSION"
      | "VERIFIER_ROLE"
      | "commitmentCount"
      | "commitments"
      | "createCommitment"
      | "freezeCommitment"
      | "getCommitment"
      | "getRole"
      | "getRoleAdmin"
      | "getWitnessCount"
      | "grantRole"
      | "hasRole"
      | "hasWitnessSigned"
      | "initialize"
      | "pause"
      | "paused"
      | "proxiableUUID"
      | "renounceRole"
      | "revokeRole"
      | "signAsSigner"
      | "signAsWitness"
      | "supportsInterface"
      | "unfreezeCommitment"
      | "unpause"
      | "upgradeToAndCall"
      | "verifyCommitment"
      | "version"
      | "witnessSigned"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CommitmentCompleted"
      | "CommitmentCreated"
      | "CommitmentFrozen"
      | "CommitmentSigned"
      | "CommitmentUnfrozen"
      | "CommitmentVerified"
      | "ContractUpgraded"
      | "Initialized"
      | "Paused"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "Unpaused"
      | "Upgraded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "EMERGENCY_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "LAWYER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "POLICE_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "VERIFIER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "commitmentCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "commitments",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createCommitment",
    values: [string, AddressLike, AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "freezeCommitment",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCommitment",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRole",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getWitnessCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasWitnessSigned",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "signAsSigner",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "signAsWitness",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unfreezeCommitment",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyCommitment",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "version", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "witnessSigned",
    values: [BigNumberish, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "EMERGENCY_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "LAWYER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "POLICE_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "VERIFIER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "commitmentCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "commitments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createCommitment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "freezeCommitment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCommitment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getWitnessCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hasWitnessSigned",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "signAsSigner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "signAsWitness",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unfreezeCommitment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyCommitment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "version", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "witnessSigned",
    data: BytesLike
  ): Result;
}

export namespace CommitmentCompletedEvent {
  export type InputTuple = [id: BigNumberish, timestamp: BigNumberish];
  export type OutputTuple = [id: bigint, timestamp: bigint];
  export interface OutputObject {
    id: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CommitmentCreatedEvent {
  export type InputTuple = [
    id: BigNumberish,
    initiator: AddressLike,
    signer: AddressLike,
    fileHash: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    initiator: string,
    signer: string,
    fileHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    id: bigint;
    initiator: string;
    signer: string;
    fileHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CommitmentFrozenEvent {
  export type InputTuple = [
    id: BigNumberish,
    freezer: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [id: bigint, freezer: string, timestamp: bigint];
  export interface OutputObject {
    id: bigint;
    freezer: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CommitmentSignedEvent {
  export type InputTuple = [
    id: BigNumberish,
    signer: AddressLike,
    role: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    signer: string,
    role: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    id: bigint;
    signer: string;
    role: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CommitmentUnfrozenEvent {
  export type InputTuple = [
    id: BigNumberish,
    unfreezer: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [id: bigint, unfreezer: string, timestamp: bigint];
  export interface OutputObject {
    id: bigint;
    unfreezer: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CommitmentVerifiedEvent {
  export type InputTuple = [
    id: BigNumberish,
    verifier: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [id: bigint, verifier: string, timestamp: bigint];
  export interface OutputObject {
    id: bigint;
    verifier: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ContractUpgradedEvent {
  export type InputTuple = [
    previousImplementation: AddressLike,
    newImplementation: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    previousImplementation: string,
    newImplementation: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    previousImplementation: string;
    newImplementation: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpgradedEvent {
  export type InputTuple = [implementation: AddressLike];
  export type OutputTuple = [implementation: string];
  export interface OutputObject {
    implementation: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CommitmentChain extends BaseContract {
  connect(runner?: ContractRunner | null): CommitmentChain;
  waitForDeployment(): Promise<this>;

  interface: CommitmentChainInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  EMERGENCY_ROLE: TypedContractMethod<[], [string], "view">;

  LAWYER_ROLE: TypedContractMethod<[], [string], "view">;

  POLICE_ROLE: TypedContractMethod<[], [string], "view">;

  UPGRADE_INTERFACE_VERSION: TypedContractMethod<[], [string], "view">;

  VERIFIER_ROLE: TypedContractMethod<[], [string], "view">;

  commitmentCount: TypedContractMethod<[], [bigint], "view">;

  commitments: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        bigint,
        boolean,
        boolean,
        bigint,
        boolean,
        boolean,
        boolean
      ] & {
        id: bigint;
        initiator: string;
        signer: string;
        fileHash: string;
        createdAt: bigint;
        initiatorSigned: boolean;
        signerSigned: boolean;
        witnessSignedCount: bigint;
        isCompleted: boolean;
        isFrozen: boolean;
        isVerified: boolean;
      }
    ],
    "view"
  >;

  createCommitment: TypedContractMethod<
    [_fileHash: string, _signer: AddressLike, _witnesses: AddressLike[]],
    [bigint],
    "nonpayable"
  >;

  freezeCommitment: TypedContractMethod<
    [_commitmentId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getCommitment: TypedContractMethod<
    [_commitmentId: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string[],
        string,
        bigint,
        boolean,
        boolean,
        bigint,
        boolean,
        boolean,
        boolean
      ] & {
        id: bigint;
        initiator: string;
        signer: string;
        witnesses: string[];
        fileHash: string;
        createdAt: bigint;
        initiatorSigned: boolean;
        signerSigned: boolean;
        witnessSignedCount: bigint;
        isCompleted: boolean;
        isFrozen: boolean;
        isVerified: boolean;
      }
    ],
    "view"
  >;

  getRole: TypedContractMethod<
    [_commitmentId: BigNumberish, _address: AddressLike],
    [string],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  getWitnessCount: TypedContractMethod<
    [_commitmentId: BigNumberish],
    [bigint],
    "view"
  >;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  hasWitnessSigned: TypedContractMethod<
    [_commitmentId: BigNumberish, _witness: AddressLike],
    [boolean],
    "view"
  >;

  initialize: TypedContractMethod<[admin: AddressLike], [void], "nonpayable">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  proxiableUUID: TypedContractMethod<[], [string], "view">;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  signAsSigner: TypedContractMethod<
    [_commitmentId: BigNumberish],
    [void],
    "nonpayable"
  >;

  signAsWitness: TypedContractMethod<
    [_commitmentId: BigNumberish],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  unfreezeCommitment: TypedContractMethod<
    [_commitmentId: BigNumberish],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  upgradeToAndCall: TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  verifyCommitment: TypedContractMethod<
    [_commitmentId: BigNumberish],
    [void],
    "nonpayable"
  >;

  version: TypedContractMethod<[], [string], "view">;

  witnessSigned: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "EMERGENCY_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "LAWYER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "POLICE_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "UPGRADE_INTERFACE_VERSION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "VERIFIER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "commitmentCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "commitments"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        bigint,
        boolean,
        boolean,
        bigint,
        boolean,
        boolean,
        boolean
      ] & {
        id: bigint;
        initiator: string;
        signer: string;
        fileHash: string;
        createdAt: bigint;
        initiatorSigned: boolean;
        signerSigned: boolean;
        witnessSignedCount: bigint;
        isCompleted: boolean;
        isFrozen: boolean;
        isVerified: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "createCommitment"
  ): TypedContractMethod<
    [_fileHash: string, _signer: AddressLike, _witnesses: AddressLike[]],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "freezeCommitment"
  ): TypedContractMethod<[_commitmentId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getCommitment"
  ): TypedContractMethod<
    [_commitmentId: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string[],
        string,
        bigint,
        boolean,
        boolean,
        bigint,
        boolean,
        boolean,
        boolean
      ] & {
        id: bigint;
        initiator: string;
        signer: string;
        witnesses: string[];
        fileHash: string;
        createdAt: bigint;
        initiatorSigned: boolean;
        signerSigned: boolean;
        witnessSignedCount: bigint;
        isCompleted: boolean;
        isFrozen: boolean;
        isVerified: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRole"
  ): TypedContractMethod<
    [_commitmentId: BigNumberish, _address: AddressLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getWitnessCount"
  ): TypedContractMethod<[_commitmentId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasWitnessSigned"
  ): TypedContractMethod<
    [_commitmentId: BigNumberish, _witness: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<[admin: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "proxiableUUID"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "signAsSigner"
  ): TypedContractMethod<[_commitmentId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "signAsWitness"
  ): TypedContractMethod<[_commitmentId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "unfreezeCommitment"
  ): TypedContractMethod<[_commitmentId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "upgradeToAndCall"
  ): TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "verifyCommitment"
  ): TypedContractMethod<[_commitmentId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "version"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "witnessSigned"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  getEvent(
    key: "CommitmentCompleted"
  ): TypedContractEvent<
    CommitmentCompletedEvent.InputTuple,
    CommitmentCompletedEvent.OutputTuple,
    CommitmentCompletedEvent.OutputObject
  >;
  getEvent(
    key: "CommitmentCreated"
  ): TypedContractEvent<
    CommitmentCreatedEvent.InputTuple,
    CommitmentCreatedEvent.OutputTuple,
    CommitmentCreatedEvent.OutputObject
  >;
  getEvent(
    key: "CommitmentFrozen"
  ): TypedContractEvent<
    CommitmentFrozenEvent.InputTuple,
    CommitmentFrozenEvent.OutputTuple,
    CommitmentFrozenEvent.OutputObject
  >;
  getEvent(
    key: "CommitmentSigned"
  ): TypedContractEvent<
    CommitmentSignedEvent.InputTuple,
    CommitmentSignedEvent.OutputTuple,
    CommitmentSignedEvent.OutputObject
  >;
  getEvent(
    key: "CommitmentUnfrozen"
  ): TypedContractEvent<
    CommitmentUnfrozenEvent.InputTuple,
    CommitmentUnfrozenEvent.OutputTuple,
    CommitmentUnfrozenEvent.OutputObject
  >;
  getEvent(
    key: "CommitmentVerified"
  ): TypedContractEvent<
    CommitmentVerifiedEvent.InputTuple,
    CommitmentVerifiedEvent.OutputTuple,
    CommitmentVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "ContractUpgraded"
  ): TypedContractEvent<
    ContractUpgradedEvent.InputTuple,
    ContractUpgradedEvent.OutputTuple,
    ContractUpgradedEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;
  getEvent(
    key: "Upgraded"
  ): TypedContractEvent<
    UpgradedEvent.InputTuple,
    UpgradedEvent.OutputTuple,
    UpgradedEvent.OutputObject
  >;

  filters: {
    "CommitmentCompleted(uint256,uint256)": TypedContractEvent<
      CommitmentCompletedEvent.InputTuple,
      CommitmentCompletedEvent.OutputTuple,
      CommitmentCompletedEvent.OutputObject
    >;
    CommitmentCompleted: TypedContractEvent<
      CommitmentCompletedEvent.InputTuple,
      CommitmentCompletedEvent.OutputTuple,
      CommitmentCompletedEvent.OutputObject
    >;

    "CommitmentCreated(uint256,address,address,string,uint256)": TypedContractEvent<
      CommitmentCreatedEvent.InputTuple,
      CommitmentCreatedEvent.OutputTuple,
      CommitmentCreatedEvent.OutputObject
    >;
    CommitmentCreated: TypedContractEvent<
      CommitmentCreatedEvent.InputTuple,
      CommitmentCreatedEvent.OutputTuple,
      CommitmentCreatedEvent.OutputObject
    >;

    "CommitmentFrozen(uint256,address,uint256)": TypedContractEvent<
      CommitmentFrozenEvent.InputTuple,
      CommitmentFrozenEvent.OutputTuple,
      CommitmentFrozenEvent.OutputObject
    >;
    CommitmentFrozen: TypedContractEvent<
      CommitmentFrozenEvent.InputTuple,
      CommitmentFrozenEvent.OutputTuple,
      CommitmentFrozenEvent.OutputObject
    >;

    "CommitmentSigned(uint256,address,string,uint256)": TypedContractEvent<
      CommitmentSignedEvent.InputTuple,
      CommitmentSignedEvent.OutputTuple,
      CommitmentSignedEvent.OutputObject
    >;
    CommitmentSigned: TypedContractEvent<
      CommitmentSignedEvent.InputTuple,
      CommitmentSignedEvent.OutputTuple,
      CommitmentSignedEvent.OutputObject
    >;

    "CommitmentUnfrozen(uint256,address,uint256)": TypedContractEvent<
      CommitmentUnfrozenEvent.InputTuple,
      CommitmentUnfrozenEvent.OutputTuple,
      CommitmentUnfrozenEvent.OutputObject
    >;
    CommitmentUnfrozen: TypedContractEvent<
      CommitmentUnfrozenEvent.InputTuple,
      CommitmentUnfrozenEvent.OutputTuple,
      CommitmentUnfrozenEvent.OutputObject
    >;

    "CommitmentVerified(uint256,address,uint256)": TypedContractEvent<
      CommitmentVerifiedEvent.InputTuple,
      CommitmentVerifiedEvent.OutputTuple,
      CommitmentVerifiedEvent.OutputObject
    >;
    CommitmentVerified: TypedContractEvent<
      CommitmentVerifiedEvent.InputTuple,
      CommitmentVerifiedEvent.OutputTuple,
      CommitmentVerifiedEvent.OutputObject
    >;

    "ContractUpgraded(address,address,uint256)": TypedContractEvent<
      ContractUpgradedEvent.InputTuple,
      ContractUpgradedEvent.OutputTuple,
      ContractUpgradedEvent.OutputObject
    >;
    ContractUpgraded: TypedContractEvent<
      ContractUpgradedEvent.InputTuple,
      ContractUpgradedEvent.OutputTuple,
      ContractUpgradedEvent.OutputObject
    >;

    "Initialized(uint64)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;

    "Upgraded(address)": TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
    Upgraded: TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
  };
}
